// Zone-based neighborhood data for the Greater Richmond metro area
// Each zone represents a "part of town" with notable communities listed underneath
// Scoring engine matches quiz answers to zones, not individual subdivisions

export interface Zone {
  id: string;
  name: string;
  oneLiner: string;
  medianPrice: string;
  priceLow: number; // in thousands, for scoring
  priceHigh: number;
  walkScore: number; // representative average for the zone
  commuteMinutes: number; // representative average
  taxRate: number; // per $100 assessed value
  schoolDistrict: string;
  county: string;
  region: "city" | "suburb" | "outer";
  settingType: "urban-core" | "established-suburb" | "new-suburb" | "rural-land";
  housingStock: string[]; // housing types available in this zone
  weeknightTags: string[]; // what's nearby on a Tuesday evening
  personas: string[];
  lifestyleTags: string[];
  vibeTags: string[];
  tradeoff: string;
  whyFitsYou: Record<string, string>; // keyed by life stage
  tagSlug: string; // for GHL tagging
  notableCommunities: string[]; // listed on results page
}

// Keep backward-compatible export name for easy migration
export type Neighborhood = Zone;

export const zones: Zone[] = [
  // ─── RICHMOND CITY ────────────────────────────────────────

  {
    id: "fan-museum",
    name: "The Fan & Museum District",
    oneLiner: "Walkable, vibrant, historic -- Richmond's urban core",
    medianPrice: "$550K-$650K",
    priceLow: 550,
    priceHigh: 650,
    walkScore: 88,
    commuteMinutes: 5,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    settingType: "urban-core",
    housingStock: ["historic-character"],
    weeknightTags: ["dining-variety", "outdoor-access"],
    personas: ["single-pro", "couple-no-kids", "remote-relocator", "empty-nester"],
    lifestyleTags: ["restaurants-nightlife", "arts-culture", "breweries-food"],
    vibeTags: ["farmers-market-brewery-dinner", "new-restaurant-live-music"],
    tradeoff: "Street parking is brutal on weekends. Older homes mean higher maintenance costs. City tax rate ($1.20) is the highest in the region. Nightlife noise carries into adjacent blocks.",
    whyFitsYou: {
      "single-pro": "You said walkability matters and nightlife is a priority. The Fan delivers both. Block after block of brick rowhouses, restaurants you walk to, and the best cocktail bars in Richmond.",
      "couple-no-kids": "Richmond's most walkable zone with the best dining scene in the city. Walk to Can Can Brasserie, catch a show at the VMFA, and be home without touching a car.",
      "remote-relocator": "Working from home in the Fan means stepping out your door to world-class restaurants, coffee shops on every block, and the VMFA when you need a break.",
      "empty-nester": "Walkable, cultured, and full of life. The VMFA, Carytown, and Byrd Park are all within walking distance. Bungalows and Cape Cods offer single-level living options.",
      default: "Richmond's flagship walkable zone. 88+ walk score, the city's best restaurant row, and block after block of historic brick rowhouses with genuine character.",
    },
    tagSlug: "match-fan-museum",
    notableCommunities: ["The Fan", "Museum District", "Monument Avenue corridor"],
  },

  {
    id: "church-hill-east",
    name: "Church Hill & East End",
    oneLiner: "Historic, revitalizing, river views -- Richmond's origin story",
    medianPrice: "$325K-$550K",
    priceLow: 325,
    priceHigh: 550,
    walkScore: 70,
    commuteMinutes: 8,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    settingType: "urban-core",
    housingStock: ["historic-character"],
    weeknightTags: ["dining-variety", "outdoor-access"],
    personas: ["single-pro", "couple-no-kids", "remote-relocator"],
    lifestyleTags: ["arts-culture", "restaurants-nightlife", "parks-trails"],
    vibeTags: ["new-restaurant-live-music", "farmers-market-brewery-dinner", "james-river-hike-brunch"],
    tradeoff: "Revitalization is real but uneven -- do your homework block by block. City tax rate applies. Some areas have limited retail within walking distance. Infrastructure still catching up to demand.",
    whyFitsYou: {
      "single-pro": "Church Hill is where American history meets Richmond's best restaurants. Sub Rosa Bakery, Alewife, The Roosevelt. Character and city views at lower prices than the Fan.",
      "couple-no-kids": "History, skyline views from Libby Hill Park, and a restaurant scene rivaling the Fan at $100-200K less per home. This zone rewards people who see what a neighborhood is becoming.",
      "remote-relocator": "Working from home with Chimborazo Park views and some of the best restaurants in Richmond. Strong appreciation potential and more house for your money than the Fan.",
      default: "Richmond's oldest neighborhood and its fastest-rising. Patrick Henry spoke here. Sub Rosa Bakery and Alewife are here now. Character, views, and appreciation potential.",
    },
    tagSlug: "match-church-hill-east",
    notableCommunities: ["Church Hill", "Shockoe Bottom", "Fulton", "Rocketts Landing"],
  },

  {
    id: "scotts-jackson",
    name: "Scott's Addition & Jackson Ward",
    oneLiner: "Breweries, urban energy, young professionals",
    medianPrice: "$380K-$550K",
    priceLow: 380,
    priceHigh: 550,
    walkScore: 82,
    commuteMinutes: 5,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    settingType: "urban-core",
    housingStock: ["historic-character", "new-construction"],
    weeknightTags: ["dining-variety"],
    personas: ["single-pro", "couple-no-kids", "remote-relocator"],
    lifestyleTags: ["breweries-food", "restaurants-nightlife", "arts-culture"],
    vibeTags: ["farmers-market-brewery-dinner", "new-restaurant-live-music"],
    tradeoff: "Noisy on weekends. Scott's Addition is mostly new construction (less historic charm). Jackson Ward revitalization is real but uneven. Limited green space in both areas. Highway projects may cause disruption.",
    whyFitsYou: {
      "single-pro": "Walk to 8 breweries, a meadery, a cidery, and a distillery without crossing a highway. Combined with Jackson Ward's First Friday art walks and Mama J's soul food. This is Richmond's social epicenter.",
      "couple-no-kids": "Richmond's hottest zone. The Veil, Brenner Pass, Lunch/Supper in Scott's Addition. Cultural depth and 85 walk score in Jackson Ward. Industrial-chic meets historic character.",
      "remote-relocator": "A national historic district meets Richmond's brewery capital. 82+ walk score, growing restaurant scene, and active revitalization. Buying into a renaissance.",
      default: "From forgotten industrial district to Richmond's hottest zone. Brewery heaven meets deep cultural roots. Creative energy and nightlife compressed into walkable blocks.",
    },
    tagSlug: "match-scotts-jackson",
    notableCommunities: ["Scott's Addition", "Jackson Ward", "Arts District"],
  },

  {
    id: "southside-city",
    name: "Southside City",
    oneLiner: "James River access, parks, emerging -- city living with green space",
    medianPrice: "$360K-$500K",
    priceLow: 360,
    priceHigh: 500,
    walkScore: 72,
    commuteMinutes: 10,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    settingType: "urban-core",
    housingStock: ["historic-character"],
    weeknightTags: ["outdoor-access", "dining-variety"],
    personas: ["family-young", "couple-no-kids", "empty-nester", "remote-relocator"],
    lifestyleTags: ["parks-trails", "arts-culture", "quiet-privacy"],
    vibeTags: ["james-river-hike-brunch", "farmers-market-brewery-dinner"],
    tradeoff: "City tax rate applies. Manchester is still developing and some blocks are early-stage. Forest Hill and Byrd Park are more established but pricier. Less nightlife energy than north-of-the-river neighborhoods.",
    whyFitsYou: {
      "family-young": "Byrd Park puts 100 acres of Maymont Estate in your backyard. Arts in the Park, Dogwood Dell concerts, Jazz at Fountain Lake. City living with the green space your family needs.",
      "couple-no-kids": "Maymont, Carytown, and the James River are all accessible. Green space and cultural events of a suburb with city walkability. Forest Hill and Byrd Park offer the best of both.",
      "empty-nester": "City walkability, world-class parks, and a quieter pace than the Fan. Diverse architecture from rowhouses to lake-view homes. Carytown is around the corner.",
      "remote-relocator": "Manchester gives you skyline views and waterfront access. Forest Hill gives you mature trees and trails. Both give you city living with room to breathe.",
      default: "Richmond's south-of-the-river zone where parks, river access, and emerging energy meet. Maymont Estate, James River trails, and Floodwall Park define daily life here.",
    },
    tagSlug: "match-southside-city",
    notableCommunities: ["Manchester", "Forest Hill", "Byrd Park", "Woodland Heights"],
  },

  {
    id: "northside-city",
    name: "Northside City",
    oneLiner: "Affordable, character homes, quirky -- Richmond's best-kept secret",
    medianPrice: "$300K-$450K",
    priceLow: 300,
    priceHigh: 450,
    walkScore: 48,
    commuteMinutes: 13,
    taxRate: 1.05,
    schoolDistrict: "Richmond City PS / Henrico County PS",
    county: "Richmond City / Henrico",
    region: "city",
    settingType: "established-suburb",
    housingStock: ["historic-character"],
    weeknightTags: ["outdoor-access"],
    personas: ["family-young", "couple-no-kids", "remote-relocator", "single-pro"],
    lifestyleTags: ["quiet-privacy", "parks-trails", "arts-culture"],
    vibeTags: ["quiet-porch-no-plans", "james-river-hike-brunch", "farmers-market-brewery-dinner"],
    tradeoff: "Lower walkability than south-of-Broad neighborhoods. Some areas are still transitioning. Lakeside is technically Henrico (lower taxes) but Ginter Park is city tax rate. Less restaurant density.",
    whyFitsYou: {
      "family-young": "Lewis Ginter Botanical Garden is your backyard. Ginter Park has some of the most beautiful tree-lined streets in Richmond. Lakeside gives you Henrico taxes at city-adjacent prices.",
      "couple-no-kids": "Ginter Park's historic homes and tree canopy rival the Fan at $150-200K less. Lakeside has quirky, artsy energy with Henrico County taxes. Best value zone in the metro.",
      "remote-relocator": "Affordable character homes, quiet streets, and Lewis Ginter Botanical Garden nearby. Lakeside's Henrico taxes save you money. Strong appreciation as the area gets discovered.",
      "single-pro": "Lakeside's quirky arts scene and Ginter Park's historic charm at prices that won't break you. Lewis Ginter Botanical Garden, Diversity Thrift, and local coffee shops define the vibe.",
      default: "Richmond's most affordable character zone. Ginter Park's tree-lined streets and Lakeside's quirky arts scene offer genuine neighborhood identity at prices well below the Fan and Church Hill.",
    },
    tagSlug: "match-northside-city",
    notableCommunities: ["Ginter Park", "Laburnum Park", "Lakeside", "Bellevue"],
  },

  {
    id: "carytown-near-west",
    name: "Carytown & Near West End",
    oneLiner: "Shopping, walkable, established -- Richmond's Main Street",
    medianPrice: "$425K-$600K",
    priceLow: 425,
    priceHigh: 600,
    walkScore: 85,
    commuteMinutes: 8,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    settingType: "urban-core",
    housingStock: ["historic-character"],
    weeknightTags: ["dining-variety", "errand-convenience"],
    personas: ["couple-no-kids", "empty-nester", "single-pro", "remote-relocator"],
    lifestyleTags: ["shopping-convenience", "restaurants-nightlife", "arts-culture"],
    vibeTags: ["farmers-market-brewery-dinner", "new-restaurant-live-music", "james-river-hike-brunch"],
    tradeoff: "City tax rate. Carytown shopping corridor gets busy on weekends. Higher price point than Church Hill or Manchester for similar square footage. Parking near shops can be challenging.",
    whyFitsYou: {
      "couple-no-kids": "Carytown is Richmond's walkable Main Street. Independent shops, restaurants, the Byrd Theatre. You're also a short walk to Byrd Park and Maymont. Everything you need is within blocks.",
      "empty-nester": "The walkability of the Fan with Carytown's shopping and dining at your doorstep. Byrd Park is around the corner. Bungalows and smaller homes fit downsizing without sacrificing lifestyle.",
      "single-pro": "Carytown's independent shops and restaurant row give you a walkable village feel. Close to Byrd Park and the Fan. Established residential streets with genuine neighborhood character.",
      "remote-relocator": "Walk to coffee shops, lunch spots, and Carytown's independent retailers. Byrd Park for afternoon breaks. One of the most complete walkable lifestyles in Richmond.",
      default: "Carytown is Richmond's walkable shopping and dining village. Independent retailers, the historic Byrd Theatre, and a strong neighborhood identity. The Near West End extends this into quiet, established residential streets.",
    },
    tagSlug: "match-carytown-west",
    notableCommunities: ["Carytown", "Near West End", "Byrd Park adjacent"],
  },

  {
    id: "west-end-city",
    name: "West End City",
    oneLiner: "Suburban feel, city address -- affordable and spacious",
    medianPrice: "$325K-$425K",
    priceLow: 325,
    priceHigh: 425,
    walkScore: 45,
    commuteMinutes: 12,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    settingType: "established-suburb",
    housingStock: ["historic-character", "turnkey-established"],
    weeknightTags: ["errand-convenience"],
    personas: ["family-young", "family-teens", "couple-no-kids", "remote-relocator"],
    lifestyleTags: ["quiet-privacy", "shopping-convenience"],
    vibeTags: ["soccer-costco-backyard", "quiet-porch-no-plans"],
    tradeoff: "City tax rate ($1.20) with suburban density -- you pay more in taxes than Henrico neighbors with similar lots. Lower walkability. Less restaurant/nightlife density. City school district.",
    whyFitsYou: {
      "family-young": "More space and larger lots than inner-city neighborhoods at lower price points. You're still in the city but with room for a yard and a garage. Close to Willow Lawn shopping.",
      "family-teens": "Affordable homes with space. Easy access to both city amenities and suburban conveniences. A bridge between city energy and suburban comfort at a price point that works.",
      "couple-no-kids": "If you want a city address with a suburban pace, the West End delivers. Bigger lots, lower prices, and easy access to Short Pump and the Fan in opposite directions.",
      "remote-relocator": "Affordable, spacious, and central. You're equidistant from downtown and Short Pump. A quiet home office with room to spread out, at prices well below the Fan.",
      default: "The western edge of Richmond City offers a suburban feel with a city address. Larger lots, lower prices, and a quiet residential pace -- though you're still paying city tax rates.",
    },
    tagSlug: "match-west-end-city",
    notableCommunities: ["West End", "Willow Lawn area", "Three Chopt corridor"],
  },

  // ─── HENRICO COUNTY ───────────────────────────────────────

  {
    id: "short-pump",
    name: "Short Pump & West Henrico",
    oneLiner: "Suburban retail hub -- shopping, dining, top schools",
    medianPrice: "$450K-$700K",
    priceLow: 450,
    priceHigh: 700,
    walkScore: 28,
    commuteMinutes: 20,
    taxRate: 0.83,
    schoolDistrict: "Henrico County PS",
    county: "Henrico",
    region: "suburb",
    settingType: "established-suburb",
    housingStock: ["turnkey-established", "new-construction"],
    weeknightTags: ["errand-convenience", "family-infrastructure", "dining-variety"],
    personas: ["family-young", "family-teens", "couple-no-kids", "remote-relocator"],
    lifestyleTags: ["shopping-convenience", "restaurants-nightlife"],
    vibeTags: ["soccer-costco-backyard"],
    tradeoff: "Cookie-cutter suburban development in some areas. Traffic on Broad Street and Route 288 during rush hour. Limited walkability -- you're driving everywhere. Higher price point than eastern Henrico.",
    whyFitsYou: {
      "family-young": "Top-rated Henrico schools, Short Pump Town Center for shopping, and every errand you can think of within 10 minutes. The family infrastructure here is unmatched in the metro.",
      "family-teens": "Henrico County schools, every restaurant chain and local spot you need, and activities for teens. Short Pump gives families everything in one place.",
      "couple-no-kids": "If dining out and easy errands matter more than walkability, Short Pump delivers. Henrico taxes ($0.83) save you $2,000-3,000/year vs. the city. Modern homes, low maintenance.",
      "remote-relocator": "Every convenience within a 10-minute drive. Henrico taxes, strong resale, and modern homes. The practical choice for people who prioritize daily ease over urban energy.",
      default: "Greater Richmond's suburban retail and family hub. Top Henrico schools, Short Pump Town Center, and every convenience imaginable. Low taxes, strong resale, and modern housing stock.",
    },
    tagSlug: "match-short-pump",
    notableCommunities: ["Short Pump", "Wellesley", "West Broad Village", "Innsbrook"],
  },

  {
    id: "glen-allen",
    name: "Glen Allen & North Henrico",
    oneLiner: "Family suburban -- community, golf, and top schools",
    medianPrice: "$450K-$750K",
    priceLow: 450,
    priceHigh: 750,
    walkScore: 20,
    commuteMinutes: 20,
    taxRate: 0.83,
    schoolDistrict: "Henrico County PS",
    county: "Henrico",
    region: "suburb",
    settingType: "established-suburb",
    housingStock: ["turnkey-established", "new-construction"],
    weeknightTags: ["family-infrastructure", "errand-convenience"],
    personas: ["family-young", "family-teens", "empty-nester", "remote-relocator"],
    lifestyleTags: ["quiet-privacy", "shopping-convenience", "parks-trails"],
    vibeTags: ["soccer-costco-backyard", "quiet-porch-no-plans"],
    tradeoff: "Low walkability -- car-dependent for everything. Suburban sameness in some developments. Further from city restaurants and nightlife. Can feel disconnected from Richmond's urban culture.",
    whyFitsYou: {
      "family-young": "Henrico County schools, community pools, soccer fields, and neighborhoods designed for families. Twin Hickory and Wyndham offer some of the best family infrastructure in the metro.",
      "family-teens": "Top-rated high schools, community amenities, and neighborhoods where teens can bike to friends' houses. Wyndham's golf community and Twin Hickory's pools are a draw.",
      "empty-nester": "Quiet, well-maintained communities with Henrico taxes. Wyndham's golf course, community amenities, and proximity to Short Pump shopping. Downsizing without sacrificing quality.",
      "remote-relocator": "Quiet neighborhoods with space for a home office. Community amenities, low taxes, and a 20-minute drive to downtown when you need it. Practical and comfortable.",
      default: "North Henrico's family-first zone. Master-planned communities, Henrico County schools, community pools, and golf. The suburban family experience done right, with low taxes.",
    },
    tagSlug: "match-glen-allen",
    notableCommunities: ["Glen Allen", "Twin Hickory", "Wyndham", "Foxhall"],
  },

  {
    id: "river-road",
    name: "River Road Corridor",
    oneLiner: "Luxury estates, close-in, Henrico taxes -- old Richmond money",
    medianPrice: "$700K-$1.2M",
    priceLow: 700,
    priceHigh: 1200,
    walkScore: 10,
    commuteMinutes: 15,
    taxRate: 0.83,
    schoolDistrict: "Henrico County PS",
    county: "Henrico",
    region: "suburb",
    settingType: "established-suburb",
    housingStock: ["historic-character", "land-acreage"],
    weeknightTags: ["outdoor-access", "solitude"],
    personas: ["couple-no-kids", "empty-nester", "family-teens"],
    lifestyleTags: ["quiet-privacy", "parks-trails"],
    vibeTags: ["quiet-porch-no-plans"],
    tradeoff: "Highest price point in the metro. Zero walkability. Exclusive and quiet, which some find isolating. Older estates may need significant renovation. Limited dining and shopping nearby.",
    whyFitsYou: {
      "couple-no-kids": "Estate-level living 15 minutes from downtown with Henrico taxes. River Road is where old Richmond money lives. Privacy, mature trees, and the James River nearby.",
      "empty-nester": "If you want space, privacy, and prestige without city taxes, River Road delivers. Mature properties on large lots with easy access to downtown and the river.",
      "family-teens": "Large lots, top Henrico schools, and the prestige of River Road. Your teens get space, privacy, and access to one of the best school districts in Virginia.",
      default: "Richmond's most prestigious address. Estate-level homes on large lots along the James River with Henrico County taxes. Quiet, private, and 15 minutes from downtown.",
    },
    tagSlug: "match-river-road",
    notableCommunities: ["River Road estates", "Windsor Farms adjacent", "Tuckahoe"],
  },

  // ─── CHESTERFIELD COUNTY ──────────────────────────────────

  {
    id: "midlothian",
    name: "Midlothian",
    oneLiner: "Established suburban, lake communities -- nature meets convenience",
    medianPrice: "$350K-$500K",
    priceLow: 350,
    priceHigh: 500,
    walkScore: 18,
    commuteMinutes: 22,
    taxRate: 0.89,
    schoolDistrict: "Chesterfield County PS",
    county: "Chesterfield",
    region: "suburb",
    settingType: "established-suburb",
    housingStock: ["turnkey-established"],
    weeknightTags: ["outdoor-access", "family-infrastructure", "errand-convenience"],
    personas: ["family-young", "family-teens", "empty-nester", "couple-no-kids"],
    lifestyleTags: ["parks-trails", "shopping-convenience", "quiet-privacy"],
    vibeTags: ["soccer-costco-backyard", "james-river-hike-brunch", "quiet-porch-no-plans"],
    tradeoff: "Car-dependent. Further from city restaurants and nightlife than Short Pump. Some communities are aging and may need updates. Route 60 corridor traffic during rush hour.",
    whyFitsYou: {
      "family-young": "Lake communities like Brandermill and Woodlake put water, trails, and pools in your backyard. Chesterfield schools, low taxes, and family amenities. Nature-adjacent suburban living.",
      "family-teens": "Established communities with teens in the neighborhood, lake access, and Chesterfield schools. Brandermill and Woodlake give families outdoor recreation without driving to it.",
      "empty-nester": "Lake living, trails, and an established community feel. Midlothian has the maturity and maintenance that newer developments lack. Low taxes and easy access to healthcare.",
      "couple-no-kids": "If outdoor access matters more than nightlife, Midlothian's lake communities deliver. Kayaking, trails, and swimming before dinner -- with Chesterfield's low tax rate.",
      default: "Chesterfield's established suburban heart. Lake communities, mature trees, and community amenities. Brandermill and Woodlake define the lifestyle: water, trails, and family infrastructure at moderate prices.",
    },
    tagSlug: "match-midlothian",
    notableCommunities: ["Brandermill", "Woodlake", "Salisbury", "Midlothian Village"],
  },

  {
    id: "moseley",
    name: "Moseley & SW Chesterfield",
    oneLiner: "New construction, master-planned -- pick your finishes and move in",
    medianPrice: "$400K-$800K",
    priceLow: 400,
    priceHigh: 800,
    walkScore: 12,
    commuteMinutes: 28,
    taxRate: 0.89,
    schoolDistrict: "Chesterfield County PS",
    county: "Chesterfield",
    region: "suburb",
    settingType: "new-suburb",
    housingStock: ["new-construction"],
    weeknightTags: ["family-infrastructure"],
    personas: ["family-young", "family-teens", "couple-no-kids"],
    lifestyleTags: ["quiet-privacy", "parks-trails", "shopping-convenience"],
    vibeTags: ["soccer-costco-backyard", "quiet-porch-no-plans"],
    tradeoff: "30+ minute commute to downtown. Very car-dependent. New developments mean construction noise and growing pains. Limited restaurant scene -- mostly chains. Infrastructure is still catching up to growth.",
    whyFitsYou: {
      "family-young": "Brand-new homes where you pick the finishes. Hallsley, Magnolia Green, and Harper's Mill are purpose-built for families: pools, trails, playgrounds, and new schools. Everything is new.",
      "family-teens": "New construction with space. Master-planned communities with amenities designed for active families. Chesterfield schools and neighborhood-level infrastructure.",
      "couple-no-kids": "If new construction and space matter more than proximity, Moseley delivers. Pick your lot, pick your finishes, and move into a home no one has lived in before.",
      default: "Greater Richmond's new-construction epicenter. Master-planned communities with modern homes, community amenities, and Chesterfield's low tax rate. The tradeoff is commute time.",
    },
    tagSlug: "match-moseley",
    notableCommunities: ["Hallsley", "Magnolia Green", "Harper's Mill", "FoxCreek"],
  },

  {
    id: "southern-chesterfield",
    name: "Southern Chesterfield",
    oneLiner: "Value and space -- more house for your money",
    medianPrice: "$325K-$425K",
    priceLow: 325,
    priceHigh: 425,
    walkScore: 10,
    commuteMinutes: 30,
    taxRate: 0.89,
    schoolDistrict: "Chesterfield County PS",
    county: "Chesterfield",
    region: "suburb",
    settingType: "new-suburb",
    housingStock: ["new-construction", "turnkey-established"],
    weeknightTags: ["family-infrastructure", "errand-convenience"],
    personas: ["family-young", "family-teens", "remote-relocator"],
    lifestyleTags: ["quiet-privacy", "shopping-convenience"],
    vibeTags: ["soccer-costco-backyard", "quiet-porch-no-plans"],
    tradeoff: "30+ minute commute to downtown. Limited dining and entertainment options. Far from city culture. Some areas feel disconnected from the rest of the metro. School quality varies by zone.",
    whyFitsYou: {
      "family-young": "The most house for your money in the metro. Newer construction, larger lots, and Chesterfield taxes. If budget is a priority and you don't need to be close to downtown, this is your zone.",
      "family-teens": "Space, affordability, and newer homes. Southern Chesterfield gives families room to grow without stretching the budget. Easy access to Route 288 and 95 corridors.",
      "remote-relocator": "If you work from home and want maximum space for minimum price, Southern Chesterfield delivers. Newer homes, large lots, and low taxes. The commute doesn't matter if you're not making it.",
      default: "Greater Richmond's value play. More square footage per dollar than anywhere else in the metro, with Chesterfield's low tax rate and growing infrastructure.",
    },
    tagSlug: "match-southern-chesterfield",
    notableCommunities: ["Chester", "Matoaca", "Ettrick", "Colonial Heights area"],
  },

  // ─── HANOVER COUNTY ───────────────────────────────────────

  {
    id: "mechanicsville",
    name: "Mechanicsville & Eastern Hanover",
    oneLiner: "Growing suburban, family values -- north side of the metro",
    medianPrice: "$325K-$500K",
    priceLow: 325,
    priceHigh: 500,
    walkScore: 15,
    commuteMinutes: 25,
    taxRate: 0.81,
    schoolDistrict: "Hanover County PS",
    county: "Hanover",
    region: "suburb",
    settingType: "established-suburb",
    housingStock: ["new-construction", "turnkey-established", "land-acreage"],
    weeknightTags: ["family-infrastructure", "errand-convenience"],
    personas: ["family-young", "family-teens", "remote-relocator"],
    lifestyleTags: ["quiet-privacy", "shopping-convenience"],
    vibeTags: ["soccer-costco-backyard", "quiet-porch-no-plans"],
    tradeoff: "25+ minute commute to downtown. Limited restaurant and nightlife scene. Very car-dependent. Can feel disconnected from Richmond's urban culture. North of the river limits options south.",
    whyFitsYou: {
      "family-young": "Hanover County schools, the lowest suburban tax rate ($0.81), and family-oriented communities. Atlee is growing with newer developments. Strong value for families prioritizing schools and taxes.",
      "family-teens": "Hanover's schools are a draw. Lower taxes than Henrico or Chesterfield. Established communities in Mechanicsville with newer options in Atlee and Studley.",
      "remote-relocator": "Hanover's low taxes and affordable homes mean more money stays in your pocket. If commute doesn't matter, you get space, quiet, and strong community at the best tax rate in the suburbs.",
      default: "Hanover County's accessible suburban zone. Lowest suburban tax rate, solid schools, and a mix of established and new-construction communities. The practical family choice north of the river.",
    },
    tagSlug: "match-mechanicsville",
    notableCommunities: ["Mechanicsville", "Atlee", "Cold Harbor", "Studley"],
  },

  {
    id: "ashland",
    name: "Ashland",
    oneLiner: "Small-town walkable, college charm -- \"the center of the universe\"",
    medianPrice: "$350K-$500K",
    priceLow: 350,
    priceHigh: 500,
    walkScore: 45,
    commuteMinutes: 30,
    taxRate: 0.81,
    schoolDistrict: "Hanover County PS",
    county: "Hanover",
    region: "suburb",
    settingType: "rural-land",
    housingStock: ["historic-character"],
    weeknightTags: ["dining-variety"],
    personas: ["couple-no-kids", "empty-nester", "remote-relocator"],
    lifestyleTags: ["arts-culture", "quiet-privacy", "breweries-food"],
    vibeTags: ["farmers-market-brewery-dinner", "quiet-porch-no-plans"],
    tradeoff: "30-minute commute to downtown Richmond. Very small -- limited dining and shopping options. Train runs through the middle of town (charm or nuisance depending on your perspective). Not truly suburban or rural -- a category of its own.",
    whyFitsYou: {
      "couple-no-kids": "A walkable small town with its own identity. Randolph-Macon College gives it cultural energy. Local shops, a brewery scene, and trains running through the center. Unlike anywhere else near Richmond.",
      "empty-nester": "Small-town walkability, Hanover taxes, and a genuine community identity. Ashland calls itself 'the center of the universe' and the people who live there believe it.",
      "remote-relocator": "If you work from home and want a walkable small town with character, Ashland is one of a kind. Coffee shops, local restaurants, and a community that knows your name.",
      default: "Ashland is its own thing. A walkable college town 30 minutes north of Richmond with Hanover County taxes, a train running through downtown, and fierce local identity. Not suburban, not rural -- just Ashland.",
    },
    tagSlug: "match-ashland",
    notableCommunities: ["Downtown Ashland", "Randolph-Macon area", "Hanover Courthouse"],
  },

  // ─── OUTER RING ───────────────────────────────────────────

  {
    id: "goochland",
    name: "Goochland",
    oneLiner: "Luxury rural estates -- the lowest taxes in the metro",
    medianPrice: "$500K-$1M+",
    priceLow: 500,
    priceHigh: 1200,
    walkScore: 5,
    commuteMinutes: 35,
    taxRate: 0.53,
    schoolDistrict: "Goochland County PS",
    county: "Goochland",
    region: "outer",
    settingType: "rural-land",
    housingStock: ["land-acreage", "historic-character"],
    weeknightTags: ["solitude", "outdoor-access"],
    personas: ["couple-no-kids", "empty-nester", "remote-relocator", "family-teens"],
    lifestyleTags: ["quiet-privacy", "parks-trails"],
    vibeTags: ["quiet-porch-no-plans"],
    tradeoff: "35+ minute commute to downtown. Zero walkability. Very limited dining, shopping, and entertainment. You're driving 20+ minutes for groceries. Must be comfortable with isolation and self-sufficiency.",
    whyFitsYou: {
      "couple-no-kids": "Estate-level living on acreage with the lowest tax rate in the metro ($0.53). If privacy, land, and quiet matter more than convenience, Goochland is the answer.",
      "empty-nester": "Land, privacy, and the lowest taxes you'll find near Richmond. Goochland offers estate living for people who are done with suburban density. The James River is nearby.",
      "remote-relocator": "If you work from home and want land, privacy, and the lowest taxes in the metro, Goochland is built for you. Fiber internet is available in many areas. No commute means no tradeoff.",
      "family-teens": "Acreage, privacy, and Goochland's small community feel. If your teens want space -- room for ATVs, horses, or just a big backyard -- this is the zone.",
      default: "Goochland is luxury rural living. Estate homes on acreage with the lowest tax rate in Greater Richmond. The tradeoff is distance from everything, but remote workers and privacy seekers don't mind.",
    },
    tagSlug: "match-goochland",
    notableCommunities: ["Goochland Courthouse", "River Road West", "Manakin-Sabot"],
  },

  {
    id: "powhatan",
    name: "Powhatan",
    oneLiner: "Rural, land, privacy -- country living near the city",
    medianPrice: "$375K-$500K",
    priceLow: 375,
    priceHigh: 500,
    walkScore: 5,
    commuteMinutes: 40,
    taxRate: 0.78,
    schoolDistrict: "Powhatan County PS",
    county: "Powhatan",
    region: "outer",
    settingType: "rural-land",
    housingStock: ["land-acreage", "new-construction"],
    weeknightTags: ["solitude"],
    personas: ["family-young", "family-teens", "remote-relocator", "couple-no-kids"],
    lifestyleTags: ["quiet-privacy", "parks-trails"],
    vibeTags: ["quiet-porch-no-plans"],
    tradeoff: "40+ minute commute to downtown. Very limited commercial infrastructure -- you're driving to Midlothian or Short Pump for most things. Rural means rural: limited internet options in some areas, volunteer fire departments.",
    whyFitsYou: {
      "family-young": "Land, space, and a tight-knit community. Powhatan gives your kids room to roam. Lower taxes than the city and a rural lifestyle that's hard to find this close to a metro area.",
      "family-teens": "If your family wants space, animals, and land, Powhatan delivers at prices below Goochland. Rural character with access to Route 288 for getting into the metro when needed.",
      "remote-relocator": "Country living 40 minutes from downtown. If you work from home and want acreage, quiet, and lower taxes, Powhatan is the affordable alternative to Goochland.",
      "couple-no-kids": "Acreage and privacy at a lower price point than Goochland. Powhatan is for people who want land and quiet without the luxury estate price tag.",
      default: "Rural living at a moderate price point. Powhatan offers acreage, privacy, and a country pace of life within reach of the Richmond metro. The affordable alternative to Goochland's estates.",
    },
    tagSlug: "match-powhatan",
    notableCommunities: ["Powhatan Courthouse", "Flat Rock", "Tobaccoville"],
  },

  {
    id: "new-kent",
    name: "New Kent & Charles City",
    oneLiner: "Eastern rural, affordable acreage -- the quiet side of Richmond",
    medianPrice: "$350K-$450K",
    priceLow: 350,
    priceHigh: 450,
    walkScore: 5,
    commuteMinutes: 40,
    taxRate: 0.72,
    schoolDistrict: "New Kent County PS / Charles City County PS",
    county: "New Kent / Charles City",
    region: "outer",
    settingType: "rural-land",
    housingStock: ["land-acreage", "new-construction"],
    weeknightTags: ["solitude", "outdoor-access"],
    personas: ["family-young", "remote-relocator", "couple-no-kids", "empty-nester"],
    lifestyleTags: ["quiet-privacy", "parks-trails"],
    vibeTags: ["quiet-porch-no-plans"],
    tradeoff: "40+ minute commute to downtown Richmond. Even more limited infrastructure than Powhatan or Goochland. Eastern corridor means less access to Short Pump and west-side amenities. Very small community feel -- not for everyone.",
    whyFitsYou: {
      "family-young": "Affordable acreage on the eastern side of the metro. New Kent offers space, low taxes ($0.72), and a growing community. Some new construction is popping up along the I-64 corridor.",
      "remote-relocator": "The most affordable acreage in the metro with some of the lowest taxes. I-64 connects you to Richmond and Williamsburg. If commute doesn't matter, the value here is hard to beat.",
      "couple-no-kids": "Land and privacy at the lowest price point in the metro. New Kent and Charles City offer eastern rural character that feels further out than it actually is.",
      "empty-nester": "If you want to slow down and spread out, New Kent and Charles City offer acreage, low taxes, and quiet. Historical character along the Route 5 corridor near the James River.",
      default: "The eastern side of Greater Richmond. Affordable acreage, low taxes, and a quiet rural lifestyle. New Kent is growing slowly along the I-64 corridor; Charles City is deeply rural and historic.",
    },
    tagSlug: "match-new-kent",
    notableCommunities: ["New Kent Courthouse", "Providence Forge", "Charles City", "Quinton"],
  },
];

// Backward-compatible export
export const neighborhoods = zones;
