// Structured neighborhood data extracted from the Richmond Relocation Guide v2
// Each neighborhood is profiled across dimensions used by the quiz scoring engine

export interface Neighborhood {
  id: string;
  name: string;
  oneLiner: string;
  medianPrice: string;
  priceLow: number; // in thousands, for scoring
  priceHigh: number;
  walkScore: number;
  commuteMinutes: number;
  taxRate: number; // per $100 assessed value
  schoolDistrict: string;
  county: string;
  region: "city" | "suburb" | "outer";
  personas: string[];
  lifestyleTags: string[];
  vibeTags: string[];
  tradeoff: string;
  whyFitsYou: Record<string, string>; // keyed by life stage
  tagSlug: string; // for GHL tagging
}

export const neighborhoods: Neighborhood[] = [
  // ─── RICHMOND CITY ────────────────────────────────────────
  {
    id: "the-fan",
    name: "The Fan & Museum District",
    oneLiner: "Walkable, vibrant, historic",
    medianPrice: "$550K-$650K",
    priceLow: 550,
    priceHigh: 650,
    walkScore: 90,
    commuteMinutes: 5,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["single-pro", "couple-no-kids", "remote-relocator"],
    lifestyleTags: ["restaurants-nightlife", "arts-culture", "breweries-food"],
    vibeTags: ["farmers-market-brewery-dinner", "new-restaurant-live-music"],
    tradeoff: "Street parking is brutal on weekends. Older homes mean higher maintenance. City tax rate ($1.20) is the highest in the region. Nightlife noise carries into adjacent blocks.",
    whyFitsYou: {
      "single-pro": "You said walkability matters and nightlife is a priority. The Fan delivers both. Block after block of brick rowhouses, restaurants you walk to, and the best cocktail bars in Richmond. It's the most walkable neighborhood in the city.",
      "couple-no-kids": "The Fan is Richmond's most walkable neighborhood with the best dining scene in the city. You and your partner can walk to Can Can Brasserie, catch a show at the VMFA, and be home without touching a car.",
      "remote-relocator": "Working from home in the Fan means stepping out your door to world-class restaurants, coffee shops on every block, and the VMFA when you need a break. Walk score of 90+ means you rarely need a car.",
      default: "The Fan is Richmond's flagship walkable neighborhood. 90+ walk score, the city's best restaurant row, and block after block of historic brick rowhouses with genuine character."
    },
    tagSlug: "match-the-fan",
  },
  {
    id: "museum-district",
    name: "Museum District",
    oneLiner: "Quieter Fan, near VMFA",
    medianPrice: "$550K-$650K",
    priceLow: 550,
    priceHigh: 650,
    walkScore: 85,
    commuteMinutes: 5,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["single-pro", "couple-no-kids", "empty-nester"],
    lifestyleTags: ["arts-culture", "quiet-privacy", "restaurants-nightlife"],
    vibeTags: ["farmers-market-brewery-dinner", "new-restaurant-live-music"],
    tradeoff: "Similar price to the Fan with slightly less nightlife energy. Still city tax rate. Parking is easier than the Fan but not effortless.",
    whyFitsYou: {
      "single-pro": "All the walkability of the Fan with a quieter, more residential feel. You're steps from the VMFA and Carytown but away from Main Street nightlife noise.",
      "couple-no-kids": "The Museum District gives you Fan-level walkability with a calmer, more residential pace. VMFA is in your backyard, and Carytown's shops and restaurants are a short walk.",
      "empty-nester": "Walkable, cultured, and quieter than the Fan. The VMFA, Carytown, and Byrd Park are all within walking distance. Bungalows and Cape Cods offer single-level living options.",
      default: "The Museum District wraps around the VMFA and offers a slightly quieter, greener version of the Fan's walkable lifestyle. Culture lovers and professionals love it here."
    },
    tagSlug: "match-museum-district",
  },
  {
    id: "church-hill",
    name: "Church Hill",
    oneLiner: "Historic, revitalizing, views",
    medianPrice: "$350K-$550K",
    priceLow: 350,
    priceHigh: 550,
    walkScore: 70,
    commuteMinutes: 10,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["single-pro", "couple-no-kids", "remote-relocator"],
    lifestyleTags: ["arts-culture", "restaurants-nightlife"],
    vibeTags: ["new-restaurant-live-music", "farmers-market-brewery-dinner"],
    tradeoff: "Some blocks are fully renovated; others are still transitioning. Do your homework block by block. City tax rate applies. Some areas have limited retail within walking distance.",
    whyFitsYou: {
      "single-pro": "Church Hill is where American history meets Richmond's best restaurants. Sub Rosa Bakery, Alewife, The Roosevelt. You get character and city views at lower prices than the Fan.",
      "couple-no-kids": "History, skyline views from Libby Hill Park, and a restaurant scene that rivals the Fan at $100-200K less per home. Church Hill rewards people who see what a neighborhood is becoming.",
      "remote-relocator": "Working from home with Chimborazo Park views and some of the best restaurants in Richmond within walking distance. Strong appreciation potential and more house for your money than the Fan.",
      default: "Richmond's oldest neighborhood and its fastest-rising. Patrick Henry spoke here. Sub Rosa Bakery and Alewife are here now. Character, views, and appreciation potential."
    },
    tagSlug: "match-church-hill",
  },
  {
    id: "scotts-addition",
    name: "Scott's Addition",
    oneLiner: "Brewery capital, industrial-chic",
    medianPrice: "$400K-$550K",
    priceLow: 400,
    priceHigh: 550,
    walkScore: 80,
    commuteMinutes: 5,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["single-pro", "couple-no-kids"],
    lifestyleTags: ["breweries-food", "restaurants-nightlife"],
    vibeTags: ["farmers-market-brewery-dinner", "new-restaurant-live-music"],
    tradeoff: "Noisy on weekends. Most housing is new construction, so you trade historic charm for modern finishes. Limited green space. Construction is ongoing.",
    whyFitsYou: {
      "single-pro": "You want to walk to 8 breweries, a meadery, a cidery, and a distillery without crossing a highway. Scott's Addition is Richmond's social epicenter for young professionals.",
      "couple-no-kids": "Richmond's hottest neighborhood. The Veil, Brenner Pass, Lunch/Supper, and more are all walkable. Industrial-chic lofts and modern construction. This is where the energy is.",
      default: "From forgotten industrial district to Richmond's hottest neighborhood. Brewery heaven, urban living, and creative energy compressed into a few walkable blocks."
    },
    tagSlug: "match-scotts-addition",
  },
  {
    id: "jackson-ward",
    name: "Jackson Ward",
    oneLiner: "Cultural, revitalizing, arts",
    medianPrice: "$380K-$475K",
    priceLow: 380,
    priceHigh: 475,
    walkScore: 85,
    commuteMinutes: 5,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["single-pro", "couple-no-kids", "remote-relocator"],
    lifestyleTags: ["arts-culture", "restaurants-nightlife"],
    vibeTags: ["new-restaurant-live-music", "farmers-market-brewery-dinner"],
    tradeoff: "Revitalization is real but uneven. Some blocks are fully transformed; others are early-stage. Highway infrastructure projects will cause disruption. Do block-level research.",
    whyFitsYou: {
      "single-pro": "The 'Harlem of the South' is writing its next chapter. First Fridays art walk, Mama J's soul food, and some of the deepest cultural roots in Richmond. Strong appreciation at 11-19% YoY.",
      "couple-no-kids": "Jackson Ward has the history, the walkability (85 walk score), and the cultural energy. You're steps from downtown and VCU with values appreciating faster than almost anywhere in the city.",
      "remote-relocator": "A national historic district with 85 walk score, growing restaurant scene, and active revitalization. You're buying into a neighborhood's renaissance at prices well below the Fan.",
      default: "Known as the 'Harlem of the South,' Jackson Ward is a national historic district with deep cultural roots, excellent walkability, and some of the strongest appreciation in Richmond."
    },
    tagSlug: "match-jackson-ward",
  },
  {
    id: "manchester",
    name: "Manchester",
    oneLiner: "Waterfront, developing, views",
    medianPrice: "$360K-$415K",
    priceLow: 360,
    priceHigh: 415,
    walkScore: 75,
    commuteMinutes: 8,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["single-pro", "couple-no-kids"],
    lifestyleTags: ["parks-trails", "arts-culture"],
    vibeTags: ["james-river-hike-brunch", "new-restaurant-live-music"],
    tradeoff: "Limited pharmacy and healthcare access. Ongoing construction. Some blocks are well-developed; others are still industrial. Block-level research is essential.",
    whyFitsYou: {
      "single-pro": "Skyline views of downtown from across the James River. Waterfront access, growing brewery scene, and prices that are $200K+ below the Fan. You're buying into appreciation potential.",
      "couple-no-kids": "Manchester gives you a skyline view of downtown, Floodwall Park at your doorstep, and James River access. The neighborhood is still writing its story, which means you're getting in early.",
      default: "Directly south of the James River from downtown. Skyline views, waterfront access, and early-adopter energy at prices well below established neighborhoods."
    },
    tagSlug: "match-manchester",
  },
  {
    id: "byrd-park",
    name: "Byrd Park",
    oneLiner: "Green, family-friendly, events",
    medianPrice: "$457K",
    priceLow: 400,
    priceHigh: 500,
    walkScore: 80,
    commuteMinutes: 8,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["family-young", "couple-no-kids", "empty-nester"],
    lifestyleTags: ["parks-trails", "arts-culture"],
    vibeTags: ["james-river-hike-brunch", "farmers-market-brewery-dinner"],
    tradeoff: "City tax rate applies. Street parking competition near events. Some blocks are quieter than others. Less nightlife than the Fan or Scott's Addition.",
    whyFitsYou: {
      "family-young": "Byrd Park puts 100 acres of Maymont Estate in your backyard. Arts in the Park, Dogwood Dell concerts, Jazz at Fountain Lake. City living with the green space your family needs.",
      "couple-no-kids": "Maymont, Carytown, and Fountain Lake are all walkable. You get the green space and cultural events of a suburb with the walkability and energy of the city.",
      "empty-nester": "Byrd Park offers city walkability, world-class parks, and a quieter pace than the Fan. Diverse architecture from rowhouses to lake-view condos. Carytown is around the corner.",
      default: "A community hub near downtown where culture, green space, and residential charm converge. Maymont Estate, Arts in the Park, and Carytown are all walkable."
    },
    tagSlug: "match-byrd-park",
  },
  {
    id: "carytown",
    name: "Carytown",
    oneLiner: "Shopping, dining, walkable",
    medianPrice: "$475K-$600K",
    priceLow: 475,
    priceHigh: 600,
    walkScore: 90,
    commuteMinutes: 8,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["single-pro", "couple-no-kids", "empty-nester"],
    lifestyleTags: ["shopping-convenience", "restaurants-nightlife", "breweries-food"],
    vibeTags: ["farmers-market-brewery-dinner", "new-restaurant-live-music"],
    tradeoff: "Premium pricing for walkability. Parking on Cary Street is competitive. City tax rate. Weekend foot traffic means noise near the main strip.",
    whyFitsYou: {
      "single-pro": "Richmond's 'Mile of Style' at your doorstep. Walk to Can Can Brasserie, boutique shops, and the Byrd Theatre. 90 walk score means you rarely need your car.",
      "couple-no-kids": "Living near Carytown means never needing a car for errands, dining, or entertainment. The walkable shopping and restaurant district is one of the best in the Southeast.",
      "empty-nester": "Carytown's walkable lifestyle is perfect for downsizing without giving up convenience. Shops, restaurants, and entertainment all within a few blocks. Urban charm with neighborhood feel.",
      default: "Richmond's 'Mile of Style.' Boutique shops, the best restaurant density in the city, and a 90 walk score. Living here means you rarely touch your car."
    },
    tagSlug: "match-carytown",
  },
  {
    id: "shockoe-bottom",
    name: "Shockoe Bottom",
    oneLiner: "Historic, nightlife, downtown",
    medianPrice: "$325K-$425K",
    priceLow: 325,
    priceHigh: 425,
    walkScore: 85,
    commuteMinutes: 3,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["single-pro", "couple-no-kids"],
    lifestyleTags: ["restaurants-nightlife", "arts-culture"],
    vibeTags: ["new-restaurant-live-music"],
    tradeoff: "Flood zone considerations. Weekend nightlife noise. Some blocks are more developed than others. Ongoing conversations about development vs. historical preservation.",
    whyFitsYou: {
      "single-pro": "The closest you can get to downtown Richmond. Loft living in converted warehouses, the 17th Street Farmers' Market, and an active nightlife corridor. Lowest entry point in the urban core.",
      "couple-no-kids": "Shockoe Bottom is where Richmond began. Historic warehouse lofts, downtown access, and the oldest public market in America. Affordable entry to city living.",
      default: "One of Richmond's most historically significant neighborhoods. Loft living, downtown access, the 17th Street Farmers' Market, and the lowest prices in the urban core."
    },
    tagSlug: "match-shockoe-bottom",
  },
  {
    id: "fulton-rocketts",
    name: "Fulton & Rocketts Landing",
    oneLiner: "Waterfront, trails, emerging",
    medianPrice: "$350K-$550K",
    priceLow: 350,
    priceHigh: 550,
    walkScore: 55,
    commuteMinutes: 12,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["single-pro", "couple-no-kids"],
    lifestyleTags: ["parks-trails", "breweries-food"],
    vibeTags: ["james-river-hike-brunch"],
    tradeoff: "Fulton outside Rocketts Landing is still early in its resurgence. Limited retail and dining beyond the waterfront corridor. You'll need a car for most errands. HOA fees in Rocketts add to costs.",
    whyFitsYou: {
      "single-pro": "Waterfront living with direct Capital Trail access and river views. Rocketts Landing is Richmond's most intentional waterfront community. Trail runners and cyclists love it here.",
      "couple-no-kids": "Modern construction with river views and the 52-mile Capital Trail starting at your doorstep. Stone Brewing and Triple Crossing are within walking distance.",
      default: "Richmond's East End riverfront. Modern waterfront living at Rocketts Landing with direct access to the Virginia Capital Trail and James River."
    },
    tagSlug: "match-fulton-rocketts",
  },
  {
    id: "laburnum-northside",
    name: "Laburnum Park & Northside",
    oneLiner: "Spacious, historic, tree-lined",
    medianPrice: "$300K-$400K",
    priceLow: 300,
    priceHigh: 400,
    walkScore: 50,
    commuteMinutes: 12,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["family-young", "couple-no-kids", "remote-relocator"],
    lifestyleTags: ["quiet-privacy", "parks-trails"],
    vibeTags: ["quiet-porch-no-plans"],
    tradeoff: "Farther from core dining and nightlife. Some blocks need more investment. City tax rate applies. Less buzz than the Fan, which means fewer walkable restaurants but better prices.",
    whyFitsYou: {
      "family-young": "Larger historic homes on bigger lots at lower prices than the Fan. Boulevard streets with mature trees. Strong value play within city limits for families who want space.",
      "couple-no-kids": "You get the historic character of the Fan with significantly more space and lower prices. American Foursquare and Colonial Revival homes on unusually large lots.",
      "remote-relocator": "Spacious historic homes with home office potential at prices $150-250K below the Fan. Tree-lined boulevard streets and a quieter pace for remote workers.",
      default: "Larger historic homes on bigger lots at lower prices than the Fan or Museum District. Boulevard streets, mature trees, and genuine architectural personality."
    },
    tagSlug: "match-laburnum-northside",
  },
  {
    id: "forest-hill",
    name: "Forest Hill",
    oneLiner: "Suburban feel, parks, families",
    medianPrice: "$375K-$475K",
    priceLow: 375,
    priceHigh: 475,
    walkScore: 60,
    commuteMinutes: 12,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["family-young", "family-teens", "couple-no-kids"],
    lifestyleTags: ["parks-trails", "quiet-privacy"],
    vibeTags: ["james-river-hike-brunch", "quiet-porch-no-plans"],
    tradeoff: "Less walkable than the Fan or Carytown. City tax rate. Fewer restaurants within walking distance. You'll need a car for most errands.",
    whyFitsYou: {
      "family-young": "Suburban feel within city limits. Forest Hill Park hosts a weekly farmers market and has trails, a lake, and playgrounds. Quieter than the Fan with easy access to both the Fan and Carytown.",
      "family-teens": "A family-friendly neighborhood with park access and a calmer pace than the urban core. Close enough to city amenities but with room to breathe.",
      default: "A suburban feel within the city. Great parks, James River access, and a weekly farmers market. Popular with families who want city living without the intensity."
    },
    tagSlug: "match-forest-hill",
  },
  {
    id: "ginter-park",
    name: "Ginter Park",
    oneLiner: "Spacious, relaxed, historic",
    medianPrice: "$350K-$450K",
    priceLow: 350,
    priceHigh: 450,
    walkScore: 55,
    commuteMinutes: 12,
    taxRate: 1.20,
    schoolDistrict: "Richmond City PS",
    county: "Richmond City",
    region: "city",
    personas: ["family-young", "couple-no-kids", "empty-nester"],
    lifestyleTags: ["parks-trails", "quiet-privacy"],
    vibeTags: ["quiet-porch-no-plans"],
    tradeoff: "Less walkable than core neighborhoods. City tax rate. Northside doesn't get the same buzz, which means less foot traffic but also less competition.",
    whyFitsYou: {
      "family-young": "Spacious historic homes on tree-lined streets near Lewis Ginter Botanical Garden. Larger lots and lower prices than comparable homes in the Fan.",
      "empty-nester": "Relaxed pace with spacious historic homes and Lewis Ginter Botanical Garden nearby. Strong community identity and active civic association.",
      default: "Spacious historic homes on tree-lined streets with a relaxed vibe. Close to Lewis Ginter Botanical Garden. Larger lots and lower prices than the Fan."
    },
    tagSlug: "match-ginter-park",
  },

  // ─── HENRICO COUNTY SUBURBS ───────────────────────────────
  {
    id: "short-pump",
    name: "Short Pump",
    oneLiner: "Shopping, dining, amenities",
    medianPrice: "$510K+",
    priceLow: 510,
    priceHigh: 650,
    walkScore: 30,
    commuteMinutes: 20,
    taxRate: 0.83,
    schoolDistrict: "Henrico County PS",
    county: "Henrico",
    region: "suburb",
    personas: ["family-young", "family-teens", "couple-no-kids"],
    lifestyleTags: ["shopping-convenience", "restaurants-nightlife"],
    vibeTags: ["soccer-costco-backyard"],
    tradeoff: "Rush hour traffic on Broad Street can be brutal. Very car-dependent. Some areas feel commercially saturated. Higher price point than other suburbs.",
    whyFitsYou: {
      "family-young": "Short Pump Town Center, top-rated Henrico schools, and every retail and dining option you could want. The tax rate is $0.83 vs. the city's $1.20, saving you thousands annually.",
      "family-teens": "Henrico County schools, Short Pump Town Center for your teens, and every convenience within a 5-minute drive. Lower taxes and newer homes than the city.",
      default: "Richmond's premier suburban hub. Top-rated Henrico schools, Short Pump Town Center, and every convenience you need. Tax rate of $0.83/$100 saves thousands vs. city living."
    },
    tagSlug: "match-short-pump",
  },
  {
    id: "glen-allen",
    name: "Glen Allen",
    oneLiner: "Newer homes, families",
    medianPrice: "$475K-$575K",
    priceLow: 475,
    priceHigh: 575,
    walkScore: 25,
    commuteMinutes: 18,
    taxRate: 0.83,
    schoolDistrict: "Henrico County PS",
    county: "Henrico",
    region: "suburb",
    personas: ["family-young", "family-teens"],
    lifestyleTags: ["shopping-convenience", "quiet-privacy"],
    vibeTags: ["soccer-costco-backyard"],
    tradeoff: "Very car-dependent. The subdivision matters more than the zip code. Two neighborhoods a mile apart can differ by $150K and be in different school zones.",
    whyFitsYou: {
      "family-young": "Newer construction, top Henrico County schools, and family-friendly neighborhoods. 18-minute commute to downtown with the $0.83 tax rate.",
      "family-teens": "Excellent school options in Henrico County. Newer homes with modern layouts. Close to Short Pump amenities without being in the thick of the traffic.",
      default: "Family-focused suburbs with newer homes, top Henrico schools, and an 18-minute commute to downtown. Tax rate savings of $0.37/$100 vs. the city."
    },
    tagSlug: "match-glen-allen",
  },
  {
    id: "wyndham",
    name: "Wyndham",
    oneLiner: "Golf, executive homes",
    medianPrice: "$550K-$750K",
    priceLow: 550,
    priceHigh: 750,
    walkScore: 15,
    commuteMinutes: 22,
    taxRate: 0.83,
    schoolDistrict: "Henrico County PS",
    county: "Henrico",
    region: "suburb",
    personas: ["family-young", "family-teens", "empty-nester"],
    lifestyleTags: ["quiet-privacy", "shopping-convenience"],
    vibeTags: ["soccer-costco-backyard", "quiet-porch-no-plans"],
    tradeoff: "Premium pricing for the area. Very car-dependent. Golf club membership is separate from home purchase. HOA fees add to monthly costs.",
    whyFitsYou: {
      "family-young": "Executive-level homes in a golf community with top Henrico schools. Wyndham is the prestige address in suburban Richmond.",
      "family-teens": "Large homes with room for the whole family. Golf, pools, and community amenities. Henrico County schools and close to Short Pump shopping.",
      "empty-nester": "Golf community living with executive homes and Henrico's lower tax rate. Established community with resort-style amenities.",
      default: "Golf community living with executive homes in Henrico County. Premium address, top schools, and resort-style amenities."
    },
    tagSlug: "match-wyndham",
  },
  {
    id: "twin-hickory",
    name: "Twin Hickory",
    oneLiner: "Family-favorite, community pools",
    medianPrice: "$450K-$550K",
    priceLow: 450,
    priceHigh: 550,
    walkScore: 20,
    commuteMinutes: 22,
    taxRate: 0.83,
    schoolDistrict: "Henrico County PS",
    county: "Henrico",
    region: "suburb",
    personas: ["family-young", "family-teens"],
    lifestyleTags: ["quiet-privacy", "shopping-convenience"],
    vibeTags: ["soccer-costco-backyard"],
    tradeoff: "Very car-dependent. HOA fees for community amenities. Rush hour traffic to downtown. Similar feel to other Henrico subdivisions.",
    whyFitsYou: {
      "family-young": "One of Henrico's most popular family neighborhoods. Community pools, walking trails, and Twin Hickory Elementary. Strong neighborhood identity with active events.",
      "family-teens": "Strong schools, community pools, and a mix of home styles. Active HOA with year-round events keeps teens engaged.",
      default: "One of Henrico's most popular family neighborhoods with community pools, walking trails, and strong schools. Active neighborhood identity."
    },
    tagSlug: "match-twin-hickory",
  },
  {
    id: "river-road",
    name: "River Road",
    oneLiner: "Estates, privacy, river",
    medianPrice: "$700K-$1.2M",
    priceLow: 700,
    priceHigh: 1200,
    walkScore: 10,
    commuteMinutes: 15,
    taxRate: 0.83,
    schoolDistrict: "Henrico County PS",
    county: "Henrico",
    region: "suburb",
    personas: ["family-young", "family-teens", "empty-nester"],
    lifestyleTags: ["quiet-privacy", "parks-trails"],
    vibeTags: ["quiet-porch-no-plans"],
    tradeoff: "Highest price point in the suburbs. Extremely car-dependent. Limited walkable retail or dining. You're paying for land, privacy, and the address.",
    whyFitsYou: {
      "family-young": "Estate-level homes on large lots with Henrico's tax rate and schools. River Road is Richmond's most prestigious suburban address.",
      "empty-nester": "Privacy, river access, and estate living with Henrico's lower tax rate. The most exclusive address in the Richmond metro at a fraction of comparable DC/NoVA homes.",
      default: "Richmond's most prestigious suburban address. Estate homes on large lots with river access, privacy, and Henrico County's favorable tax rate."
    },
    tagSlug: "match-river-road",
  },

  // ─── CHESTERFIELD COUNTY SUBURBS ──────────────────────────
  {
    id: "midlothian",
    name: "Midlothian",
    oneLiner: "Value, families, parks",
    medianPrice: "$420K-$500K",
    priceLow: 420,
    priceHigh: 500,
    walkScore: 20,
    commuteMinutes: 20,
    taxRate: 0.89,
    schoolDistrict: "Chesterfield County PS",
    county: "Chesterfield",
    region: "suburb",
    personas: ["family-young", "family-teens"],
    lifestyleTags: ["shopping-convenience", "parks-trails"],
    vibeTags: ["soccer-costco-backyard"],
    tradeoff: "Flies under the radar. Not the flashiest address. Commute to downtown via Powhite adds toll costs. Less dining variety than Short Pump.",
    whyFitsYou: {
      "family-young": "Dollar for dollar, Midlothian gives you more house than almost anywhere in the metro. Chesterfield schools, parks, and a $0.89 tax rate. The smart value play.",
      "family-teens": "Strong Chesterfield schools including Cosby High. More house for the money than Henrico. Lake access at Brandermill and Woodlake nearby.",
      default: "Dollar for dollar, you get a lot of house in Midlothian. Chesterfield schools, parks, and a tax rate that saves thousands vs. the city. Richmond's best-kept suburban secret."
    },
    tagSlug: "match-midlothian",
  },
  {
    id: "moseley",
    name: "Moseley",
    oneLiner: "Master-planned, new builds",
    medianPrice: "$450K-$550K",
    priceLow: 450,
    priceHigh: 550,
    walkScore: 10,
    commuteMinutes: 30,
    taxRate: 0.89,
    schoolDistrict: "Chesterfield County PS",
    county: "Chesterfield",
    region: "suburb",
    personas: ["family-young", "family-teens"],
    lifestyleTags: ["quiet-privacy", "shopping-convenience"],
    vibeTags: ["soccer-costco-backyard", "quiet-porch-no-plans"],
    tradeoff: "Still building out. Ongoing construction means traffic and noise. Dining scene doesn't match Short Pump yet. 25-30+ minute commute to downtown. Strict HOA rules.",
    whyFitsYou: {
      "family-young": "Master-planned communities like Hallsley and Magnolia Green with new construction, community pools, and Chesterfield schools. Everything is brand new.",
      "family-teens": "New construction with modern layouts. Community amenities, pools, and Cosby High School district. More space than comparable Henrico homes.",
      default: "Master-planned communities with brand-new construction, community amenities, and Chesterfield schools. Everything is new and designed for families."
    },
    tagSlug: "match-moseley",
  },
  {
    id: "brandermill",
    name: "Brandermill",
    oneLiner: "Lake living, established",
    medianPrice: "$375K-$475K",
    priceLow: 375,
    priceHigh: 475,
    walkScore: 15,
    commuteMinutes: 22,
    taxRate: 0.89,
    schoolDistrict: "Chesterfield County PS",
    county: "Chesterfield",
    region: "suburb",
    personas: ["family-young", "family-teens", "empty-nester"],
    lifestyleTags: ["parks-trails", "quiet-privacy"],
    vibeTags: ["james-river-hike-brunch", "quiet-porch-no-plans"],
    tradeoff: "Established community means older homes that may need updates. HOA fees for lake and community access. Car-dependent. Less modern than new-build communities.",
    whyFitsYou: {
      "family-young": "Lake living without leaving the metro. 17+ miles of trails, community pools, and Swift Creek Reservoir access. Affordable entry to lakefront living.",
      "family-teens": "Lake access, trails, and an established community with year-round events. Clover Hill High School district.",
      "empty-nester": "Peaceful lake living with an established community feel. 17+ miles of trails and Swift Creek Reservoir. Affordable and quiet.",
      default: "Lake living in the Richmond metro. 17+ miles of trails, Swift Creek Reservoir, and an established community with year-round events."
    },
    tagSlug: "match-brandermill",
  },

  // ─── HANOVER COUNTY ───────────────────────────────────────
  {
    id: "mechanicsville",
    name: "Mechanicsville",
    oneLiner: "Affordability, space",
    medianPrice: "$375K-$450K",
    priceLow: 375,
    priceHigh: 450,
    walkScore: 15,
    commuteMinutes: 25,
    taxRate: 0.81,
    schoolDistrict: "Hanover County PS",
    county: "Hanover",
    region: "suburb",
    personas: ["family-young", "family-teens"],
    lifestyleTags: ["quiet-privacy", "shopping-convenience"],
    vibeTags: ["soccer-costco-backyard", "quiet-porch-no-plans"],
    tradeoff: "Longer commute to downtown. Limited dining and entertainment compared to Henrico. Very car-dependent. Less diverse housing stock.",
    whyFitsYou: {
      "family-young": "The math works: $0.81 tax rate and $375-450K medians. Over 10 years, that's $15,600 in tax savings vs. Richmond City. Hanover County schools and more space per dollar.",
      "family-teens": "Hanover County schools, more house for your money, and the lowest tax rate in the inner suburbs. Mechanicsville is the closest Hanover suburb to downtown.",
      default: "Affordability meets space. $0.81 tax rate, Hanover County schools, and the closest Hanover suburb to downtown at 25 minutes."
    },
    tagSlug: "match-mechanicsville",
  },
  {
    id: "ashland",
    name: "Ashland",
    oneLiner: "Small-town charm, walkable downtown",
    medianPrice: "$425K-$500K",
    priceLow: 425,
    priceHigh: 500,
    walkScore: 45,
    commuteMinutes: 30,
    taxRate: 0.81,
    schoolDistrict: "Hanover County PS",
    county: "Hanover",
    region: "suburb",
    personas: ["family-young", "couple-no-kids", "empty-nester", "remote-relocator"],
    lifestyleTags: ["breweries-food", "quiet-privacy"],
    vibeTags: ["farmers-market-brewery-dinner", "quiet-porch-no-plans"],
    tradeoff: "30-minute commute to downtown. The train literally runs through the middle of town (charming but noisy if you're near the tracks). Small-town retail means limited options.",
    whyFitsYou: {
      "family-young": "Ashland is Richmond's charming college town. Walkable downtown, Center of the Universe Brewing, and Hanover schools. Small-town identity with $0.81 tax rate.",
      "couple-no-kids": "A walkable small-town downtown with independent shops, great restaurants, and a brewery. Randolph-Macon College gives it a unique energy. Distinctly different from cookie-cutter suburbs.",
      "remote-relocator": "If you work remote and want small-town charm with walkable amenities, Ashland is your answer. Coffee shops, restaurants, and a brewery all walkable from downtown. 30 min to Richmond when you need it.",
      "empty-nester": "Walkable small-town living with charm, culture, and community. Ashland has its own identity that's completely different from suburban Richmond.",
      default: "Richmond's charming college town. Walkable downtown with independent shops, Center of the Universe Brewing, and a unique small-town identity."
    },
    tagSlug: "match-ashland",
  },

  // ─── OUTER RING ───────────────────────────────────────────
  {
    id: "goochland",
    name: "Goochland",
    oneLiner: "Estates, horses, luxury",
    medianPrice: "$500K+",
    priceLow: 500,
    priceHigh: 900,
    walkScore: 5,
    commuteMinutes: 35,
    taxRate: 0.53,
    schoolDistrict: "Goochland County PS",
    county: "Goochland",
    region: "outer",
    personas: ["family-young", "empty-nester", "remote-relocator"],
    lifestyleTags: ["quiet-privacy", "parks-trails"],
    vibeTags: ["quiet-porch-no-plans"],
    tradeoff: "35-minute commute minimum. Extremely car-dependent. No walkable retail or dining. Rural character means fewer amenities. Limited school options.",
    whyFitsYou: {
      "remote-relocator": "Some of the most beautiful properties in the Richmond metro sit on 10+ acres with James River views, and they cost less than a townhouse in DC. If you've got remote work flexibility, this is where your money goes furthest.",
      "family-young": "Land, privacy, and the lowest tax rate in the region at $0.53/$100. Estate properties with acreage for families who want space and don't mind the drive.",
      "empty-nester": "Luxury estate living with rolling farmland, James River views, and the lowest taxes in the metro. Goochland is the luxury sleeper of Richmond.",
      default: "The luxury sleeper of Richmond. 5-25 acre estates with James River views at prices below a DC townhouse. Lowest tax rate in the metro at $0.53/$100."
    },
    tagSlug: "match-goochland",
  },
  {
    id: "powhatan",
    name: "Powhatan",
    oneLiner: "Rural, farmland, quiet",
    medianPrice: "$375K-$500K",
    priceLow: 375,
    priceHigh: 500,
    walkScore: 5,
    commuteMinutes: 40,
    taxRate: 0.78,
    schoolDistrict: "Powhatan County PS",
    county: "Powhatan",
    region: "outer",
    personas: ["family-young", "empty-nester", "remote-relocator"],
    lifestyleTags: ["quiet-privacy", "parks-trails"],
    vibeTags: ["quiet-porch-no-plans"],
    tradeoff: "40-minute commute to downtown. Very rural. Extremely limited retail, dining, and entertainment. You're choosing land and quiet over convenience.",
    whyFitsYou: {
      "remote-relocator": "Most acreage per dollar in the Richmond metro. Genuinely rural character with rolling farmland and state forest access. Perfect for remote workers who want land.",
      "family-young": "2-10 acre lots with a rural lifestyle. Powhatan County schools and a small-town county seat. Best for families from rural areas who want to maintain that lifestyle near Richmond.",
      "empty-nester": "Peaceful rural living with acreage, farmland character, and low taxes. Semi-retired or retired buyers seeking quiet living close to Richmond.",
      default: "The most acreage per dollar in the Richmond metro. Genuinely rural character with rolling farmland and state forest access. 40 minutes to downtown."
    },
    tagSlug: "match-powhatan",
  },
];
